---
title: "2014 Congressional Election Results"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
library(DT)
library(leaflet)
library(leaflet.extras)
opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  cache = TRUE,
  cache.path = here("cache/2014_cong/"))
```

```{r process data, include = FALSE}
# read in cd 11 ed shape file
cd11_ed_sf <- read_sf(here("output/geo/cd11_ed_2014.geojson")) %>%
  mutate(elect_dist = as.character(elect_dist))

# read in pres results 2014
cong_2014 <- read_csv(
  here("output/elect_results/2014_cd11.csv"),
  col_types = cols(year = "i", total_votes = "i", .default = "c")) %>%
  mutate_at(vars(ends_with("_prop")), as.double) %>%
  mutate_at(vars(ends_with("_tot")), as.integer)

# create dem/rep margins
cong_2014_margin <- cong_2014 %>%
  mutate(margin = recchia_prop - grimm_prop) %>%
  select(elect_dist, total_votes, margin, recchia_tot,
         grimm_tot, recchia_prop, grimm_prop)

cong_2014_to_map <- left_join(cd11_ed_sf, cong_2014_margin) %>%
  mutate(elect_dist = paste("ED", elect_dist))

cong_2014_close_rep <- cong_2014_to_map %>%
  filter(margin >= -0.1 & margin < 0)

cong_2014_close_dem <- cong_2014_to_map %>%
  filter(margin >= 0 & margin <= 0.1)

# define a little helper function to format percentages
make_pct <- function(x, digits = 1) {
  paste0(formatC(x * 100, digits = digits, format = "f"), "%")
}

# define a little helper function to format margins
make_margin <- function(x, digits = 1) {
  if_else(x > 0,
          paste0("+",formatC(x * 100, digits = digits, format = "f")),
          formatC(x * 100, digits = digits, format = "f")
          )
}
```

### NY 11 results at the election district-level

<span style="background-color:lightgreen">Green outlines</span> indicate election districts that lean Republican (between -10 and 0 point margin)  
<span style="background-color:orange">Orange outlines</span> indicate election districts that lean Democratic (between 0 and +10 point margin)  
Click an ED for details 

```{r make map, cache = FALSE, message = FALSE, out.width = "100%", out.height = "600px"}

# make a map of margin, highlight ed +-10pt
tmap_mode("view")
map <- tm_shape(cong_2014_to_map, name = "2014 Congressional") +
  tm_fill(
    col = "margin",
    palette = "RdBu",
    style = "cont",
    breaks = seq(-1, 1, by = 0.2),
    title = "D/R Margin",
    textNA = "No Votes",
    popup.vars = c(
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes",
      "Recchia %" = "recchia_prop",
      "Grimm %" = "grimm_prop"
    ),
    id = "elect_dist",
    popup.format = list(
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0),
      recchia_prop = list(fun = make_pct),
      grimm_prop = list(fun = make_pct)
      )
  ) +
  tm_borders(col = "darkgray") +
  tm_shape(cong_2014_close_dem, name = "Lean Dem") +
  tm_borders(col = "orange", lwd = 2) +
  tm_shape(cong_2014_close_rep, name = "Lean Rep") +
  tm_borders(col = "green", lwd = 2) +
  tm_view(
    alpha = 0.85,
    basemaps = "Stamen.TonerLite",
    legend.position = c("right", "bottom")
    )

tmap_leaflet(map) %>%
  addSearchFeatures(
    targetGroups = "2014 Congressional",
    options = searchFeaturesOptions(
      zoom = 14,
      openPopup = TRUE,
      collapsed = FALSE,
      position = "topright",
      textPlaceholder = "Search EDs..."
      )
    ) %>%
  addFullscreenControl(pseudoFullscreen = TRUE)
```

### NY 11 Summary
```{r table}
tot <- cong_2014_margin %>%
  summarise(
    `Recchia` = sum(recchia_tot, na.rm = TRUE),
    Grimm = sum(grimm_tot, na.rm = TRUE),
    Total = sum(total_votes, na.rm = TRUE),
    `Recchia %` = make_pct(`Recchia` / Total),
    `Grimm %` = make_pct(Grimm / Total),
    `Lean Rep EDs` = sum((margin >= -0.1 & margin < 0), na.rm = TRUE),
    `Lean Dem EDs` = sum((margin >= 0 & margin <= 0.1), na.rm = TRUE)
  )

kable(
  tot,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```

### Swing District Detail
*EDs between -10 and +10 margin*  
<br>
```{r data_table, cache = FALSE}
to_table <- cong_2014_margin %>%
  filter(between(margin, -0.1, 0.1)) %>%
  mutate(
    lean = if_else(
      (margin >= -0.1 & margin < 0), "Republican", "Democratic"
      ),
    margin = margin * 100
    ) %>%
  select(elect_dist, margin, lean, total_votes,
         recchia_prop, grimm_prop, everything()) %>%
  arrange(margin)

datatable(
  to_table,
  class = "row-border hover",
  rownames = FALSE,
  colnames = c("Election District", "Margin", "Lean", "Total Votes",
               "Recchia %", "Grimm %", "Recchia", "Grimm"),
  extensions = c("Buttons", "Scroller", "Responsive"),
  options = list(
    dom = "Bfrtip",
    buttons = c("csv", "print"),
    deferRender = TRUE,
    scrollY = "370px",
    scroller = TRUE
    )
  ) %>%
  formatPercentage(5:6, 1) %>%
  formatRound(2, 1) %>%
  formatStyle(
  "margin",
  target = "row",
  backgroundColor = styleInterval(c(0), c("#FFF5F5", "#F5F9FF"))
)
```


