---
title: "2016 Congressional Election Results"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
opts_chunk$set(echo = FALSE, cache = TRUE, cache.path = here("cache/2016_cong/"))
```

```{r process data, include = FALSE}
# read in cd 11 ed shape file
cd11_ed_sf <- read_sf(here("data/geo/cd11_ed.geojson"))

# read in results
cong_2016 <- read_csv(
  here("output/elect_results/2016_cd11.csv"),
  col_types = cols(year = "i", total_votes = "i", .default = "c")) %>%
  mutate_at(vars(ends_with("_prop")), as.double) %>%
  mutate_at(vars(ends_with("_tot")), as.integer)

# create dem/rep margins, join with ed geo file
cong_2016_margin <- cong_2016 %>%
  mutate(margin = reichard_prop - donovan_prop) %>%
  select(elect_dist, total_votes, margin, reichard_tot,
         donovan_tot, reichard_prop, donovan_prop)

cong_2016_to_map <- left_join(cd11_ed_sf, cong_2016_margin) %>%
  mutate(elect_dist = paste("ED", elect_dist))

cong_2016_close_ed <- cong_2016_to_map %>%
  filter(between(margin, -.1, .1))

# define a little helper function to format percentages
make_pct <- function(x, digits = 1) {
  paste0(formatC(x * 100, digits = digits, format = "f"), "%")
}

# define a little helper function to format margins
make_margin <- function(x, digits = 1) {
  if_else(x > 0,
          paste0("+",formatC(x * 100, digits = digits, format = "f")),
          formatC(x * 100, digits = digits, format = "f")
          )
}
```

Results for CD 11 at the election distrcit level. Green outlines indicate election district margins within &#177;10 points. Click on an ED for more details.  

```{r make map, message = FALSE, out.width = "100%", out.height = "600px"}

# make a map of reichard/donovan margin 2016, highlight ed +-10pt
tmap_mode("view")
tm_shape(cong_2016_to_map, name = "2016 Congressional") +
  tm_fill(
    col = "margin",
    palette = "RdBu",
    style = "cont",
    breaks = seq(-1, 1, by = 0.2),
    title = "D/R Margin",
    textNA = "No Votes",
    popup.vars = c(
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes",
      "Reichard %" = "reichard_prop",
      "Donovan %" = "donovan_prop"
    ),
    id = "elect_dist",
    popup.format = list(
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0),
      reichard_prop = list(fun = make_pct),
      donovan_prop = list(fun = make_pct)
      )
  ) +
  tm_borders(col = "darkgray") +
  tm_shape(cong_2016_close_ed, name = "Close EDs") +
  tm_borders(col = "green", lwd = 2)
```
<br>
```{r table}
tot <- cong_2016_margin %>%
  summarise(
    Reichard = sum(reichard_tot, na.rm = TRUE),
    Donovan = sum(donovan_tot, na.rm = TRUE),
    Total = sum(total_votes, na.rm = TRUE),
    `Reichard %` = make_pct(Reichard / Total),
    `Donovan %` = make_pct(Donovan / Total),
    `Close EDs` = sum(between(margin, -.1, .1), na.rm = TRUE)
  )

kable(
  tot,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```

