---
title: "CTC Target Districts Map"
output: html_document
---

```{r setup, include = FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
library(DT)
library(tmaptools)
library(leaflet)
library(leaflet.extras)
opts_chunk$set(echo = FALSE, cache = TRUE, cache.path = here("cache/2016_pres_van/"))
```

```{r process data, include = FALSE}
# read in cd 11 ed shape file
cd11_ed_sf <- read_sf(here("output/geo/van_ed_demo.geojson"))
cd11_ed_all_sf <- read_sf(here("output/geo/cd11_demo_2016.geojson"))

# read in pres results 2016
pres_2016 <- read_csv(
  here("output/elect_results/2016_pres.csv"),
  col_types = cols(year = "i", total_votes = "i", .default = "c")) %>%
  mutate_at(vars(ends_with("_prop")), as.double) %>%
  mutate_at(vars(ends_with("_tot")), as.integer)

# read in turnout 2016
turnout <-
  read_csv(
  here("output/2016_turnout_si.csv"),
  col_types = cols(elect_dist = "c", turnout_reg_prop = "d", .default = "i")
  ) %>%
  rename(total_votes_role = total_votes)

# create dem/rep margins foron, join with ed geo file
pres_2016_margin <- 
  pres_2016 %>%
  mutate(margin = clinton_prop - trump_prop) %>%
  select(elect_dist, total_votes, margin, clinton_tot,
         trump_tot, clinton_prop, trump_prop)

pres_2016_to_map <-
  left_join(cd11_ed_sf, pres_2016_margin) %>%
  left_join(turnout, by = "elect_dist") %>%
  mutate(elect_dist = paste("ED", elect_dist))

pres_2016_all_to_map <- left_join(cd11_ed_all_sf, pres_2016_margin) %>%
  left_join(turnout, by = "elect_dist") %>%
  mutate(elect_dist = paste("ED", elect_dist))

# define a little helper function to format percentages
make_pct <- function(x, digits = 1) {
  paste0(formatC(x * 100, digits = digits, format = "f"), "%")
}

# define a little helper function to format $$
make_dollar <- function(x, digits = 0) {
  paste0("$", formatC(x, digits = digits, format = "f", big.mark = ","))
}

# define a little helper function to format margins
make_margin <- function(x, digits = 1) {
  if_else(x > 0,
          paste0("+",formatC(x * 100, digits = digits, format = "f")),
          formatC(x * 100, digits = digits, format = "f")
          )
}
```

<span style="background-color:lightgreen">Highlighted districts</span> (`r nrow(pres_2016_to_map)`) are included in CTC's NGP VAN Database
```{r make map, cache = FALSE, message = FALSE, out.width = "100%", out.height = "600px"}
# make a map of clinton/trump margin 2016, highlight ed +-10pt
tmap_mode("view")
layer_cd11 <- 
  tm_shape(pres_2016_all_to_map, name = "CD 11") +
  tm_fill(
    col = "#D4D4D4",
    id = "elect_dist",
    popup.vars = c(
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes",
      "Turnout (% of reg voters)" = "turnout_reg_prop",
      "Clinton %" = "clinton_prop",
      "Trump %" = "trump_prop",
      "Median HH Income" = "med_hhinc",
      "% Bachelors" = "pop_ba_pct",
      "% White" = "pop_white_adj_pct"
    ),
    popup.format = list(
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0),
      turnout_reg_prop = list(fun = make_pct),
      clinton_prop = list(fun = make_pct),
      trump_prop = list(fun = make_pct),
      med_hhinc = list(fun = make_dollar),
      pop_ba_pct = list(fun = make_pct),
      pop_white_adj_pct = list(fun = make_pct)
      )
    ) +
  tm_borders(col = "darkgray")
  
layer_pres2016 <- 
  tm_shape(pres_2016_to_map, name = "2016 Presidential") +
  tm_fill(
    col = "margin",
    palette = "RdBu",
    style = "cont",
    alpha = 0.65,
    breaks = seq(-0.5, 0.5, by = 0.2),
    title = "D/R Margin",
    textNA = "No Votes",
    id = "elect_dist",
    popup.vars = c(
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes",
      "Turnout (% of reg voters)" = "turnout_reg_prop",
      "Clinton %" = "clinton_prop",
      "Trump %" = "trump_prop",
      "Median HH Income" = "med_hhinc",
      "% Bachelors" = "pop_ba_pct",
      "% White" = "pop_white_adj_pct"
    ),
    popup.format = list(
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0),
      turnout_reg_prop = list(fun = make_pct),
      clinton_prop = list(fun = make_pct),
      trump_prop = list(fun = make_pct),
      med_hhinc = list(fun = make_dollar),
      pop_ba_pct = list(fun = make_pct),
      pop_white_adj_pct = list(fun = make_pct)
      )
  ) +
  tm_borders(col = "lightgreen", lwd = 2)

layer_turnout <- 
  tm_shape(pres_2016_to_map, name = "2016 Turnout") +
  tm_fill(
    col = "turnout_reg_prop",
    palette = "Oranges",
    style = "cont",
    alpha = 0.65,
    contrast = c(0, 1),
    title = "Median HH Income",
    textNA = "No Data",
    id = "elect_dist",
    popup.vars = c(
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes",
      "Turnout (% of reg voters)" = "turnout_reg_prop",
      "Clinton %" = "clinton_prop",
      "Trump %" = "trump_prop",
      "Median HH Income" = "med_hhinc",
      "% Bachelors" = "pop_ba_pct",
      "% White" = "pop_white_adj_pct"
    ),
    popup.format = list(
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0),
      turnout_reg_prop = list(fun = make_pct),
      clinton_prop = list(fun = make_pct),
      trump_prop = list(fun = make_pct),
      med_hhinc = list(fun = make_dollar),
      pop_ba_pct = list(fun = make_pct),
      pop_white_adj_pct = list(fun = make_pct)
      ),
    legend.show = FALSE
  ) +
  tm_borders(col = "lightgreen", lwd = 2)

layer_income <- 
  tm_shape(pres_2016_to_map, name = "HH Income") +
  tm_fill(
    col = "med_hhinc",
    palette = "Purples",
    style = "cont",
    alpha = 0.65,
    contrast = c(0.2, 1),
    title = "Median HH Income",
    textNA = "No Data",
    popup.vars = c(
      "Median HH Income" = "med_hhinc",
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes"
    ),
    id = "elect_dist",
    popup.format = list(
      med_hhinc = list(fun = make_dollar),
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0)
      ),
    legend.show = FALSE
  ) +
  tm_borders(col = "lightgreen", lwd = 2)

layer_white <- 
  tm_shape(pres_2016_to_map, name = "% White") +
  tm_fill(
    col = "pop_white_adj_pct",
    palette = "-RdPu",
    style = "cont",
    alpha = 0.65,
    contrast = c(0, 0.8),
    title = "% White",
    textNA = "No Data",
    popup.vars = c(
      "% White" = "pop_white_adj_pct",
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes"
    ),
    id = "elect_dist",
    legend.show = FALSE,
    popup.format = list(
      pop_white_adj_pct = list(fun = make_pct),
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0)
      )
  ) +
  tm_borders(col = "lightgreen", lwd = 2)

layer_edu <- 
  tm_shape(pres_2016_to_map, name = "% Bachelors") +
  tm_fill(
    col = "pop_ba_pct",
    palette = "Blues",
    style = "cont",
    alpha = 0.65,
    contrast = c(0, 0.8),
    title = "% Bachelors",
    textNA = "No Data",
    popup.vars = c(
      "% Bachelors" = "pop_ba_pct",
      "Dem/Rep Margin" = "margin",
      "Total Votes" = "total_votes"
    ),
    id = "elect_dist",
    legend.show = FALSE,
    popup.format = list(
      pop_ba_pct = list(fun = make_pct),
      margin = list(fun = make_margin),
      total_votes = list(format = "f", digits = 0)
      )
  ) +
  tm_borders(col = "lightgreen", lwd = 2)

tm_options <- tm_view(
    alpha = 0.85,
    basemaps = "Stamen.TonerLite",
    legend.position = c("right", "bottom")
    )

leaf_map <- tmap_leaflet(
  layer_cd11 +
    layer_pres2016 +
    layer_turnout +
    layer_income +
    layer_edu +
    layer_white +
    tm_options
  )

leaf_map %>% 
    addLayersControl(
      baseGroups = c(
        "2016 Presidential",
        "2016 Turnout",
        "HH Income",
        "% White",
        "% Bachelors"
        ),
      options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addSearchFeatures(
    targetGroups  = "CD 11",
    options = searchFeaturesOptions(
      zoom = 14,
      openPopup = TRUE,
      collapsed = FALSE,
      position = "topright",
      textPlaceholder = "Search EDs...",
      hideMarkerOnCollapse = TRUE,
      textErr = "ED Not Found"
      )
    ) %>%
  addFullscreenControl(pseudoFullscreen = TRUE)

```

### NY 11 Summary
```{r summary table}
tot <- pres_2016_margin %>%
  summarise(
    Clinton = sum(clinton_tot, na.rm = TRUE),
    Trump = sum(trump_tot, na.rm = TRUE),
    Total = sum(total_votes, na.rm = TRUE),
    `Clinton %` = make_pct(Clinton / Total),
    `Trump %` = make_pct(Trump / Total)
  )

kable(
  tot,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```


### District Detail
```{r data_table, cache = FALSE}
to_table <- pres_2016_to_map %>%
  mutate(
    lean = if_else(
      (margin >= -1 & margin < 0), "Republican", "Democratic"
      ),
    margin = margin * 100
    ) %>%
  select(elect_dist, margin, total_votes, turnout_reg_prop, med_hhinc,
         pop_white_adj_pct, pop_ba_pct, pop_rent_pct,
         clinton_prop, trump_prop) %>%
  arrange(margin) %>%
  st_set_geometry(NULL)

datatable(
  to_table,
  class = "row-border hover",
  rownames = FALSE,
  colnames = c("ED", "Margin", "Total Votes", "Turnout %", 
               "Median HH Income", "White %", "Bachelors %", "Renters %",
               "Clinton %", "Trump %"),
  extensions = c("Buttons", "Scroller", "Responsive"),
  options = list(
    dom = "Bfrtip",
    language = list(search = "Filter:"),
    buttons = c("csv", "print"),
    deferRender = TRUE,
    scrollY = "370px",
    scroller = TRUE
    )
  ) %>%
  formatPercentage(c(4, 6:9), 1) %>%
  formatRound(2, 1) %>%
  formatCurrency(5, digits = 0) %>%
  formatStyle(
  "margin",
  target = "row",
  backgroundColor = styleInterval(c(0), c("#FFF5F5", "#F5F9FF"))
)
```