---
title: "2016 Election Results and Demographics"
output: html_document
---

```{r setup, include = FALSE}
##### LOAD MY LIBRARIES #####

library(tidyverse)
library(janitor)
library(lubridate)
library(here)
library(sf)
library(tmap)
library(mapview)
library(leaflet)
library(leaflet.extras)
library(knitr)
library(kableExtra)
library(DT)

##### DEFINE HELPER FUNCTIONS #####

# define a little helper function to format percentages
make_pct <- function(x, digits = 1) {
  paste0(formatC(x * 100, digits = digits, format = "f"), "%")
}

# define a little helper function to format margins
make_margin <- function(x, digits = 1) {
  if_else(x > 0,
          paste0("+",formatC(x * 100, digits = digits, format = "f")),
          formatC(x * 100, digits = digits, format = "f")
  )
}

# define a little helper function to format $$
make_dollar <- function(x, digits = 0) {
  paste0("$", formatC(x, digits = digits, format = "f", big.mark = ","))
}

# add basemap to tmaps
add_basemap <- 
  tm_view(
    alpha = 0.85,
    basemaps = "Stamen.TonerLite",
    legend.position = c("right", "bottom")
  )

# define van districts for filtering

current_van <- c(
  "46035",
  "46047",
  "46049",
  "46050",
  "46051",
  "46052",
  "46053",
  "46066",
  "46067",
  "46068",
  "46069",
  "46070",
  "46071",
  "47002",
  "47005",
  "47006",
  "49047",
  "49048",
  "49049",
  "49051",
  "49052",
  "63011",
  "63013",
  "63016",
  "63024",
  "63053",
  "63055",
  "63060",
  "63069",
  "63068",
  "63056",
  "63054",
  "61024",
  "61039",
  "61038",
  "63003",
  "63061",
  "63073",
  "63074",
  "64043",
  "64045",
  "64046",
  "64047",
  "61052",
  "64053",
  "64038"
)
opts_chunk$set(echo = FALSE, cache = TRUE, cache.path = here("cache/2016_pres_new/"))
```

```{r process data 2016, include = FALSE}
# read in cd 11 ed shape file
cd11_ed_all_sf <- read_sf(here("output/geo/cd11_demo_2016.geojson"))

# read in pres results 2016
pres_2016 <-
  read_csv(
  here("output/elect_results/2016_pres.csv"),
  col_types = cols(year = "i", total_votes = "i", .default = "c")) %>%
  mutate_at(vars(ends_with("_prop")), as.double) %>%
  mutate_at(vars(ends_with("_tot")), as.integer)

cong_2016 <-
  read_csv(
  here("output/elect_results/2016_cd11.csv"),
  col_types = cols(year = "i", total_votes = "i", .default = "c")) %>%
  mutate_at(vars(ends_with("_prop")), as.double) %>%
  mutate_at(vars(ends_with("_tot")), as.integer)

# read in turnout 2016
turnout <-
  read_csv(
  here("output/2016_turnout_si.csv"),
  col_types = cols(elect_dist = "c", turnout_reg_prop = "d", .default = "i")) %>%
  rename(total_votes_role = total_votes)

# create dem/rep margins foron, join with ed geo file
pres_2016_margin <- 
  pres_2016 %>%
  mutate(margin = clinton_prop - trump_prop) %>%
  select(elect_dist, total_votes, margin, clinton_tot,
         trump_tot, clinton_prop, trump_prop)

# create dem/rep margins foron, join with ed geo file
cong_2016_margin <- 
  cong_2016 %>%
  mutate(margin_cong = reichard_prop - donovan_prop) %>%
  select(elect_dist, margin_cong, total_votes_cong = total_votes,
         reichard_tot, donovan_tot, reichard_prop, donovan_prop)

cd11_2016_all_to_map <-
  left_join(cd11_ed_all_sf, pres_2016_margin) %>%
  left_join(cong_2016_margin) %>%
  left_join(turnout, by = "elect_dist")

cd11_2016_van_to_map <- cd11_2016_all_to_map %>%
  filter(elect_dist %in% current_van)
```

```{r process data 2014, include = FALSE}
# read in cd 11 ed shape file
cd11_ed_14 <- read_sf(here("output/geo/cd11_ed_2014.geojson"))

# read in pres results 2012
cong_2014 <- read_csv(
  here("output/elect_results/2014_cd11.csv"),
  col_types = cols(year = "i", total_votes = "i", .default = "c")) %>%
  mutate_at(vars(ends_with("_prop")), as.double) %>%
  mutate_at(vars(ends_with("_tot")), as.integer)

cong_2014_margin <- cong_2014 %>%
  mutate(margin = recchia_prop - grimm_prop) %>%
  select(elect_dist, total_votes, margin, recchia_tot,
         grimm_tot, recchia_prop, grimm_prop)

cong_2014_to_map <- left_join(cd11_ed_14, cong_2014_margin) %>%
  mutate(elect_dist = paste("ED", elect_dist))
```


```{r process data 2012, include = FALSE}
# read in cd 11 ed shape file
cd11_ed_12 <- read_sf(here("output/geo/cd11_ed_2012.geojson"))

# read in pres results 2012
pres_2012 <- read_csv(
  here("output/elect_results/2012_pres.csv"),
  col_types = cols(year = "i", total_votes = "i", .default = "c")) %>%
  mutate_at(vars(ends_with("_prop")), as.double) %>%
  mutate_at(vars(ends_with("_tot")), as.integer)

# create dem/rep margins, join with ed geo file
pres_2012_margin <- pres_2012 %>%
  mutate(margin = obama_prop - romney_prop) %>%
  select(elect_dist, total_votes, margin, obama_tot,
         romney_tot, obama_prop, romney_prop)

pres_2012_to_map <- left_join(cd11_ed_12, pres_2012_margin) %>%
  mutate(elect_dist = paste("ED", elect_dist))
```

**Highlighted districts** (`r nrow(cd11_2016_van_to_map)`) are included in CTC's NGP VAN Database
```{r make map, cache = FALSE, message = FALSE, out.width = "100%", out.height = "600px"}
# define popup vars and formating
popup.vars <- c(
  "Pres Margin" = "margin",
  "Cong Margin" = "margin_cong",
  "Total Votes" = "total_votes",
  "Registered Voters" = "total_reg",
  "Turnout (% of reg voters)" = "turnout_reg_prop",
  "Clinton %" = "clinton_prop",
  "Trump %" = "trump_prop",
  "Median HH Income" = "med_hhinc",
  "% Bachelors" = "pop_ba_pct",
  "% White" = "pop_white_adj_pct"
  )

popup.format <- list(
  margin = list(fun = make_margin),
  margin_cong = list(fun = make_margin),
  total_votes = list(format = "f", digits = 0),
  total_reg = list(format = "f", digits = 0),
  turnout_reg_prop = list(fun = make_pct),
  clinton_prop = list(fun = make_pct),
  trump_prop = list(fun = make_pct),
  med_hhinc = list(fun = make_dollar),
  pop_ba_pct = list(fun = make_pct),
  pop_white_adj_pct = list(fun = make_pct)
  )

# define popup vars and formating
popup.vars.12 <- c(
  "Pres Margin" = "margin",
  "Total Votes" = "total_votes",
  #"Registered Voters" = "total_reg",
  #"Turnout (% of reg voters)" = "turnout_reg_prop",
  "Obama %" = "obama_prop",
  "Romney %" = "romney_prop"
  )

popup.format.12 <- list(
  margin = list(fun = make_margin),
 # margin_cong = list(fun = make_margin),
  total_votes = list(format = "f", digits = 0),
  #total_reg = list(format = "f", digits = 0),
  #turnout_reg_prop = list(fun = make_pct),
  obama_prop = list(fun = make_pct),
  romney_prop = list(fun = make_pct)
  )

# define popup vars and formating
popup.vars.14 <- c(
  "Pres Margin" = "margin",
  "Total Votes" = "total_votes",
  #"Registered Voters" = "total_reg",
  #"Turnout (% of reg voters)" = "turnout_reg_prop",
  "Recchia %" = "recchia_prop",
  "Grimm %" = "grimm_prop"
  )

popup.format.14 <- list(
  margin = list(fun = make_margin),
 # margin_cong = list(fun = make_margin),
  total_votes = list(format = "f", digits = 0),
  #total_reg = list(format = "f", digits = 0),
  #turnout_reg_prop = list(fun = make_pct),
  recchia_prop = list(fun = make_pct),
  grimm_prop = list(fun = make_pct)
  )

# make a map of clinton/trump margin 2016, highlight ed +-10pt
layer_pres <- 
  tm_shape(cd11_2016_all_to_map, name = "2016 President") +
  tm_fill(
    col = "margin",
    palette = "RdBu",
    style = "cont",
    id = "elect_dist",
    title = "2016 President",
    popup.vars = popup.vars,
    popup.format = popup.format,
    legend.show = FALSE
    ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "2016 President") +
  tm_borders("black", lwd = 1.5)

layer_cong <- 
  tm_shape(cd11_2016_all_to_map, name = "2016 House") +
  tm_fill(
    col = "margin_cong",
    palette = "RdBu",
    style = "cont",
    id = "elect_dist",
    popup.vars = popup.vars,
    popup.format = popup.format,
    legend.show = FALSE
    ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "2016 House") +
  tm_borders("black", lwd = 1.5)

layer_cong_14 <- 
  tm_shape(cong_2014_to_map, name = "2014 House") +
  tm_fill(
    col = "margin",
    palette = "RdBu",
    style = "cont",
    id = "elect_dist",
    popup.vars = popup.vars.14,
    popup.format = popup.format.14,
    legend.show = FALSE
    ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "2014 House") +
  tm_borders("black", lwd = 1.5)

layer_turnout <- 
  tm_shape(cd11_2016_all_to_map, name = "2016 Turnout") +
  tm_fill(
    col = "turnout_reg_prop",
    palette = "Oranges",
    style = "cont",
    id = "elect_dist",
    popup.vars = popup.vars,
    popup.format = popup.format,
    legend.show = FALSE
  ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "2016 Turnout") +
  tm_borders("black", lwd = 1.5)

layer_pres_12 <- 
  layer_income <- 
  tm_shape(pres_2012_to_map, name = "2012 Presidential") +
  tm_fill(
    col = "margin",
    palette = "RdBu",
    style = "cont",
    contrast = c(0.2, 1),
    id = "elect_dist",
    popup.vars = popup.vars.12,
    popup.format = popup.format.12,
    legend.show = FALSE
  ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "2012 Presidential") +
  tm_borders("black", lwd = 1.5)

layer_income <- 
  tm_shape(cd11_2016_all_to_map, name = "HH Income") +
  tm_fill(
    col = "med_hhinc",
    palette = "Purples",
    style = "cont",
    contrast = c(0.2, 1),
    id = "elect_dist",
    popup.vars = popup.vars,
    popup.format = popup.format,
    legend.show = FALSE
  ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "HH Income") +
  tm_borders("black", lwd = 1.5)

layer_white <- 
  tm_shape(cd11_2016_all_to_map, name = "% White") +
  tm_fill(
    col = "pop_white_adj_pct",
    palette = "-RdPu",
    style = "cont",
    contrast = c(0, 0.8),
    id = "elect_dist",
    popup.vars = popup.vars,
    popup.format = popup.format,
    legend.show = FALSE
  ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "% White") +
  tm_borders("black", lwd = 1.5)

layer_edu <- 
  tm_shape(cd11_2016_all_to_map, name = "% Bachelors") +
  tm_fill(
    col = "pop_ba_pct",
    palette = "Blues",
    style = "cont",
    contrast = c(0, 0.8),
    id = "elect_dist",
    popup.vars = popup.vars,
    popup.format = popup.format,
    legend.show = FALSE
  ) +
  tm_borders(col = "darkgray") +
  tm_shape(cd11_2016_van_to_map, name = "% Bachelors") +
  tm_borders("black", lwd = 1.5)

map_layers <-
    layer_pres +
    layer_pres_12 +
    layer_cong +
    layer_cong_14 +
    layer_turnout +
    layer_income +
    layer_edu +
    layer_white +
    add_basemap

leaf_map <- tmap_leaflet(map_layers) %>%
  addFullscreenControl(pseudoFullscreen = TRUE) %>%
  addLayersControl(
    baseGroups = c(
      "2016 President",
      "2012 Presidential",
      "2016 House",
      "2014 House",
      "2016 Turnout",
      "HH Income",
      "% White",
      "% Bachelors"
      ),
    options = layersControlOptions(collapsed = FALSE)
    ) %>% 
    addSearchFeatures(
    targetGroups = "2016 President",
    options = searchFeaturesOptions(
      zoom = 14,
      openPopup = TRUE,
      collapsed = FALSE,
      position = "topright",
      textPlaceholder = "Search EDs..."
      )
    )

leaf_map

# leaf_pres <-
#   tmap_leaflet(layer_pres + add_basemap) %>%
#   addLegend(
#     pal = colorNumeric(palette = "RdBu", domain = c(-1, 1)),
#     values = c(-1, 1),
#     group = "2016 President"
#     )
# 
# leaf_turn <-
# tmap_leaflet(layer_turnout + add_basemap) %>%
#   addLegend(
#     pal = colorNumeric(palette = "Oranges", domain = c(0, 1)),
#     values = c(0, 1),
#     group = "2016 Turnout"
#     )


```
<br>

#### 2016 President
```{r pres table}
tot <- pres_2016_margin %>%
  summarise(
    Clinton = sum(clinton_tot, na.rm = TRUE),
    Trump = sum(trump_tot, na.rm = TRUE),
    Total = sum(total_votes, na.rm = TRUE),
    Margin = make_margin((Clinton / Total) - (Trump / Total)),
    `Clinton %` = make_pct(Clinton / Total),
    `Trump %` = make_pct(Trump / Total),
    `Turnout (% of reg voters)` = make_pct(
      sum(total_votes[elect_dist %in% turnout$elect_dist], na.rm = TRUE) /
        sum(turnout$total_reg)
      )
    )

kable(
  tot,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```
#### 2012 President
```{r pres 12 table}
tot_pres_12 <- pres_2012_margin %>%
  summarise(
    Obama = sum(obama_tot, na.rm = TRUE),
    Romney = sum(romney_tot, na.rm = TRUE),
    Total = sum(total_votes, na.rm = TRUE),
    Margin = make_margin((Obama / Total) - (Romney / Total)),
    `Obama %` = make_pct(Obama / Total),
    `Romney %` = make_pct(Romney / Total),
    # `Turnout (% of reg voters)` = make_pct(
    #   sum(total_votes_cong[elect_dist %in% turnout$elect_dist], na.rm = TRUE) /
    #     sum(turnout$total_reg)
    #   )
    )

kable(
  tot_pres_12,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```

#### 2016 House
```{r cong table}
tot_cong <- cong_2016_margin %>%
  summarise(
    Reichard = sum(reichard_tot, na.rm = TRUE),
    Donovan = sum(donovan_tot, na.rm = TRUE),
    Total = sum(total_votes_cong, na.rm = TRUE),
    Margin = make_margin((Reichard / Total) - (Donovan / Total)),
    `Reichard %` = make_pct(Reichard / Total),
    `Donovan %` = make_pct(Donovan / Total),
    `Turnout (% of reg voters)` = make_pct(
      sum(total_votes_cong[elect_dist %in% turnout$elect_dist], na.rm = TRUE) /
        sum(turnout$total_reg)
      )
    )

kable(
  tot_cong,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```

#### 2014 House
```{r cong 14 table}
tot_cong_14 <- cong_2014_margin %>%
  summarise(
    Recchia = sum(recchia_tot, na.rm = TRUE),
    Grimm = sum(grimm_tot, na.rm = TRUE),
    Total = sum(total_votes, na.rm = TRUE),
    Margin = make_margin((Recchia / Total) - (Grimm / Total)),
    `Recchia %` = make_pct(Recchia / Total),
    `Grimm %` = make_pct(Grimm / Total),
    # `Turnout (% of reg voters)` = make_pct(
    #   sum(total_votes_cong[elect_dist %in% turnout$elect_dist], na.rm = TRUE) /
    #     sum(turnout$total_reg)
    #   )
    )

kable(
  tot_cong_14,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```


#### NY 11 Demographics
```{r demo table}
tot_demo <- cd11_2016_all_to_map %>%
  st_set_geometry(NULL) %>%
  summarise(
    `Median HH Income` = make_dollar(median(med_hhinc, na.rm = TRUE)),
    `% Bachelors` = make_pct(
      sum(pop_ba_adj, na.rm = TRUE) / sum(pop_ba_denom_adj, na.rm = TRUE)
      ),
    `% White` = make_pct(
      sum(pop_white_adj, na.rm = TRUE) / sum(pop_tot_adj, na.rm = TRUE)
      ),
  )

kable(
  tot_demo,
  format = "html",
  format.args = list(big.mark = ','),
  align = "c"
  ) %>%
  kable_styling(full_width = FALSE, position = "left")
```

### District Detail
```{r data_table, cache = FALSE, out.width = "120%"}
to_table <- cd11_2016_all_to_map %>%
  filter(elect_dist %in% current_van) %>% 
  mutate(
    margin = margin * 100,
    margin_cong = margin_cong * 100) %>%
  select(elect_dist, margin, margin_cong, total_votes, total_reg,
         turnout_reg_prop, med_hhinc,
         pop_white_adj_pct, pop_ba_pct,
         clinton_prop, trump_prop, reichard_prop, donovan_prop) %>%
  arrange(margin) %>%
  st_set_geometry(NULL)

datatable(
  to_table,
  class = "row-border hover",
  rownames = FALSE,
  colnames = c("ED", "Margin", "House Margin", "Total Votes",
               "Registered Voters", "Turnout %",
               "Median HH Income", "White %", "Bachelors %",
               "Clinton %", "Trump %", "Reichard %", "Donovan %"),
  extensions = c("Buttons", "Scroller", "Responsive"),
  options = list(
    dom = "Bfrtip",
    language = list(search = "Filter:"),
    buttons = c("csv", "print"),
    deferRender = TRUE,
    scrollY = "370px",
    scroller = TRUE
    )
  ) %>%
  formatPercentage(c(6, 8:11), 1) %>%
  formatRound(2:3, 1) %>%
  formatCurrency(7, digits = 0) %>%
  formatStyle(
  "margin",
  target = "row",
  backgroundColor = styleInterval(c(0), c("#FFF5F5", "#F5F9FF"))
)
```